apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-project
  template:
    metadata:
      labels:
        app: node-project
        labels: "0"
    spec:
      containers:
        - name: node-project
          image: bikeshrestha/srpbsm-node-project:latest
          envFrom:
            - configMapRef:
                name: node-project-config-v1
---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-node
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30082
  selector:
    app: node-project
    labels: "0"
  type: NodePort
